// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZyPasxTDAOru-ZsH6R0f4byPoHGZoKic',
    appId: '1:871797340538:ios:1b756e8b4f00577a167ec3',
    messagingSenderId: '871797340538',
    projectId: 'littermate-f0eb9',
    storageBucket: 'littermate-f0eb9.firebasestorage.app',
    androidClientId: '871797340538-4fc68gndip8428949tee9j2oloiucv0n.apps.googleusercontent.com',
    iosClientId: '871797340538-1rn7su3jg198fih66q2fg5dc14d2up2t.apps.googleusercontent.com',
    iosBundleId: 'com.breedly.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTbYfwJaZovfFCgky_0pygFW1jvS558U',
    appId: '1:871797340538:android:315a4706be868526167ec3',
    messagingSenderId: '871797340538',
    projectId: 'littermate-f0eb9',
    storageBucket: 'littermate-f0eb9.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY2pMbq8GgaUnZDeNT9Pt2laL6d9ANFV0',
    appId: '1:871797340538:web:83602a955a3d809c167ec3',
    messagingSenderId: '871797340538',
    projectId: 'littermate-f0eb9',
    authDomain: 'littermate-f0eb9.firebaseapp.com',
    storageBucket: 'littermate-f0eb9.firebasestorage.app',
    measurementId: 'G-2S0K1MXFM5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZyPasxTDAOru-ZsH6R0f4byPoHGZoKic',
    appId: '1:871797340538:ios:472ec66533b63cc8167ec3',
    messagingSenderId: '871797340538',
    projectId: 'littermate-f0eb9',
    storageBucket: 'littermate-f0eb9.firebasestorage.app',
    androidClientId: '871797340538-4fc68gndip8428949tee9j2oloiucv0n.apps.googleusercontent.com',
    iosClientId: '871797340538-rqa78cv8dtmr9l4hgrvmiaua6gb2skn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.breedly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY2pMbq8GgaUnZDeNT9Pt2laL6d9ANFV0',
    appId: '1:871797340538:web:e2e937586860237a167ec3',
    messagingSenderId: '871797340538',
    projectId: 'littermate-f0eb9',
    authDomain: 'littermate-f0eb9.firebaseapp.com',
    storageBucket: 'littermate-f0eb9.firebasestorage.app',
    measurementId: 'G-8J996ZC63Z',
  );

}
