// Dog breeds from NKK Sandefjord June 2026
// Extracted from official judging list
const List<String> dogBreeds = [
  // Gruppe 1 - Herding Dogs
  'Australian Kelpie',
  'Australian Stumpy Tail Cattle Dog',
  'Bearded Collie',
  'Border Collie',
  'Bouvier Des Ardennes',
  'Bouvier Des Flandres',
  'Briard',
  'Chodsky Pes',
  'Hvit Gjeterhund',
  'Old English Sheepdog',
  'Polsk Owczarek Nizinny',
  'Romanian Carpathian Shepherd Dog',
  'Romanian Mioritic Shepherd Dog',
  'Schipperke',
  'Schäferhund Normalhår',
  'Schäferhund Langhår',
  'Shetland Sheepdog',
  'Welsh Corgi Cardigan',
  'Welsh Corgi Pembroke',
  'Belgisk Fårehund, Groenendael',
  'Belgisk Fårehund, Laekenois',
  'Belgisk Fårehund, Malinois',
  'Belgisk Fårehund, Tervueren',
  'Collie Korthåret',
  'Collie Langhåret',
  'Australian Cattledog',
  'Australian Shepherd',
  'Beauceron',
  'Bergamasco',
  'Katalansk Gjeterhund',
  'Kroatisk Gjeterhund',
  'Lancashire Heeler',
  'Mallorcansk Gjeterhund',
  'Maremma',
  'Miniature American Shepherd',
  'Picard',
  'Polsk Owczarek Podhalanski',
  'Portugisisk Gjeterhund',
  'Pyreneisk Gjeterhund',
  'Pyreneisk Gjeterhund M/Korth.Hode',
  'Schapendoes',
  'Slovakisk Cuvac',
  'Sydrussisk Ovtcharka',
  'Saarloos Wolfhond',
  'Vostochno-Evropeiskaya Ovcharka',
  'Komondor',
  'Kuvasz',
  'Mudi',
  'Puli',
  'Pumi',
  'Hollandsk Gjeterhund, Korthåret',
  'Hollandsk Gjeterhund, Langhåret',
  'Hollandsk Gjeterhund, Strihåret',
  // Gruppe 2 - Pinscher, Schnauzer, Molossian Dogs
  'Aidi',
  'Azores Cattledog',
  'Boxer',
  'Bullmastiff',
  'Castro Laboreirohund',
  'Cimarron Uruguayan',
  'Ciobanesc Romanesc De Bucovina',
  'Continental Bulldog',
  'Dansk-Svensk Gårdshund',
  'Dobermann',
  'Engelsk Bulldog',
  'Engelsk Mastiff',
  'Grand Danois',
  'Hovawart',
  'Kangal Coban Köpegi',
  'Karst Gjeterhund',
  'Kaukasisk Ovtcharka',
  'Landseer',
  'Leonberger',
  'Napolitansk Mastiff',
  'Newfoundlandshund',
  'Presa Canario',
  'Pyreneerhund',
  'Pyreneisk Mastiff',
  'Rafeiro Do Alentejo',
  'Rottweiler',
  'Russisk Sort Terrier',
  'Sarplaninac',
  'Sentralasiatisk Ovtcharka',
  'Serra Da Estrelahund',
  'Serra Da Estrelahund, Korthåret',
  'Smoushond',
  'Spansk Mastiff',
  'Tornjak',
  'Østerriksk Pinscher',
  'Appenzeller Sennenhund',
  'Berner Sennenhund',
  'Entlebucher Sennenhund',
  'Grosser Schweizer Sennenhund',
  'Sankt Bernhardshund Korthåret',
  'Sankt Bernhardshund Langhåret',
  'Dvergschnauzer Hvit',
  'Dvergschnauzer Salt/Pepper',
  'Dvergschnauzer Sort',
  'Dvergschnauzer Sort/Silver',
  'Riesenschnauzer Salt/Pepper',
  'Riesenschnauzer Sort',
  'Riesenschnauzer Sort/Sølv',
  'Schnauzer Salt/Pepper',
  'Schnauzer Sort',
  'Affenpinscher',
  'Dvergpinscher',
  'Pinscher',
  'Bordeaux Dogge',
  'Broholmer',
  'Cane Corso',
  'Perro Dogo Mallorquin',
  'Shar Pei',
  'Tibetansk Mastiff',
  // Gruppe 3 - Terriers
  'Amerikansk Naken Terrier',
  'Biewer Terrier',
  'Rat Terrier',
  'Tenterfield Terrier',
  'Toy Fox Terrier',
  'Airedale Terrier',
  'Bedlington Terrier',
  'Border Terrier',
  'Bull Terrier',
  'Fox Terrier Glatthåret',
  'Fox Terrier Ruhåret',
  'Irish Softcoated Wheaten Terrier',
  'Irsk Terrier',
  'Kerry Blue Terrier',
  'Lakeland Terrier',
  'Manchester Terrier',
  'Miniature Bull Terrier',
  'Nihon Teria',
  'Parson Russell Terrier',
  'Staffordshire Bull Terrier',
  'Terrier Brasileiro',
  'Tysk Jaktterrier',
  'Welsh Terrier',
  'Australsk Terrier',
  'Cairn Terrier',
  'Cesky Terrier',
  'Dandie Dinmont Terrier',
  'Irish Glen Of Imaal Terrier',
  'Jack Russell Terrier',
  'Norfolk Terrier',
  'Norwich Terrier',
  'Sealyham Terrier',
  'Skotsk Terrier',
  'Skye Terrier',
  'West Highland White Terrier',
  'Engelsk Toy Terrier',
  'Silky Terrier',
  'Yorkshire Terrier',
  // Gruppe 4 - Dachshunds
  'Dachshund Korthåret',
  'Dachshund Langhåret',
  'Dachshund Strihåret',
  'Dvergdachshund Korthåret',
  'Dvergdachshund Langhåret',
  'Dvergdachshund Strihåret',
  'Kanindachshund Korthåret',
  'Kanindachshund Langhåret',
  'Kanindachshund Strihåret',
  // Gruppe 5 - Spitz and Primitive Types
  'American Akita',
  'American Eskimo Dog',
  'Basenji',
  'Canadian Eskimo Dog',
  'Canaanhund',
  'Chow Chow',
  'Dansk Spitz',
  'Etnahund',
  'Eurasier',
  'Faraohund',
  'Finsk Spets',
  'Grosspitz',
  'Islandsk Fårehund',
  'Keeshond',
  'Kintamani-Bali Dog',
  'Kleinspitz',
  'Koreansk Jindo',
  'Mittelspitz',
  'Norrbottenspets',
  'Norsk Buhund',
  'Norsk Lundehund',
  'Peruviansk Nakenhund Medium',
  'Peruviansk Nakenhund Miniatyr',
  'Peruviansk Nakenhund Standard',
  'Podenco Canario',
  'Podengo Portugues Liten Glatthåret',
  'Podengo Portugues Liten Strihåret',
  'Podengo Portugues Mellom Glatthåret',
  'Podengo Portugues Mellom Strihåret',
  'Podengo Portugues Stor Glatthåret',
  'Podengo Portugues Stor Strihåret',
  'Pomeranian',
  'Taiwan Dog',
  'Thai Bangkaew Dog',
  'Thai Ridgeback Dog',
  'Volpino Italiano',
  'Västgötaspets',
  'Xoloitzcuintle Liten',
  'Xoloitzcuintle Mellom',
  'Xoloitzcuintle Stor',
  'Hälleforshund',
  'Jämthund',
  'Karelsk Bjørnhund',
  'Norsk Elghund Grå',
  'Norsk Elghund Sort',
  'Russisk Europeisk Laika',
  'Svensk Hvit Elghund',
  'Vestsibirsk Laika',
  'Yakutian Laika',
  'Østsibirsk Laika',
  'Alaskan Malamute',
  'Grønlandshund',
  'Samojedhund',
  'Siberian Husky',
  'Finsk Lapphund',
  'Lapsk Vallhund',
  'Svensk Lapphund',
  'Akita',
  'Hokkaido',
  'Japansk Spisshund',
  'Kai',
  'Kishu',
  'Shiba',
  'Shikoku',
  'Podenco Ibicenco Glatthåret',
  'Podenco Ibicenco Strihåret',
  // Gruppe 6 - Scent Hounds
  'Amerikansk Foxhound',
  'Anglo-Russisk Støver',
  'Black And Tan Coonhound',
  'Blodhund',
  'Bluetick Coonhound',
  'Brandlbracke',
  'Dalmatiner',
  'Estonian Hound',
  'Foxhound',
  'Harrier',
  'Istarski Korthåret Støver',
  'Istarski Strihåret Støver',
  'Otterhound',
  'Plott',
  'Polish Hunting Dog',
  'Rhodesian Ridgeback',
  'Steiersk Ruhåret Bracke',
  'Tiroler Bracke',
  'Tysk Bracke',
  'Westfalsk Dachsbracke',
  'Basset Artesien Normand',
  'Basset Bleu De Gascogne',
  'Basset Fauve De Bretagne',
  'Basset Hound',
  'Grand Basset Griffon Vendeen',
  'Petit Basset Griffon Vendeen',
  'Dunker',
  'Finsk Støver',
  'Gotlandsstøver',
  'Haldenstøver',
  'Hamiltonstøver',
  'Hygenhund',
  'Schillerstøver',
  'Smålandsstøver',
  'Ariégois',
  'Artoishund',
  'Balkanstøver',
  'Beagle Harrier',
  'Bernerstøver',
  'Billy',
  'Bosnisk Strihåret Støver',
  'Briquet Griffon Vendéen',
  'Erdélyi Kopo',
  'Estlandsstøver',
  'Fransk Hvit Og Gul Støver',
  'Fransk Hvit Og Sort Støver',
  'Fransk Trefarget Støver',
  'Gascon Saintongeois (stor Og Liten)',
  'Grand Bleu De Gascogne',
  'Grand Griffon Vendéen',
  'Gresk Støver',
  'Griffon Bleu De Gascogne',
  'Griffon Fauve De Bretagne',
  'Griffon Nivernais',
  'Italiensk Korthåret Støver',
  'Italiensk Strihåret Støver',
  'Jugoslavisk Trefarget Støver',
  'Jurastøver',
  'Liten Anglo-Fransk Støver',
  'Liten Bernerstøver',
  'Liten Jurastøver',
  'Liten Luzernerstøver',
  'Liten Schweizerstøver',
  'Luzernerstøver',
  'Petit Bleu De Gascogne',
  'Poitevin',
  'Polsk Støver',
  'Porcelaine',
  'Posavina Støver',
  'Russisk Flekket Støver',
  'Russisk Støver',
  'Schweizerstøver',
  'Slovakisk Støver',
  'Slovensk Bergstøver',
  'Spansk Støver',
  'Stor Anglo-Fransk Hvit/Gul Støver',
  'Stor Anglo-Fransk Hvit/Sort Støver',
  'Stor Anglo-Fransk Trefarget Støver',
  'Treeing Walker Coonhound',
  'Alpinsk Dachsbracke',
  'Bayersk Viltsporhund',
  'Hannoveransk Viltsporhund',
  'Beagle',
  'Drever',
  // Gruppe 7 - Pointing Dogs
  'Breton',
  'Epagneul De Saint-Usuge',
  'Grosser Münsterländer',
  'Kleiner Münsterländer',
  'Vorstehhund Korthåret',
  'Vorstehhund Langhåret',
  'Vorstehhund Stikkelhåret',
  'Vorstehhund Strihåret',
  'Engelsk Setter',
  'Gordon Setter',
  'Irsk Rød Og Hvit Setter',
  'Irsk Setter',
  'Pointer',
  'Blå Picardie Spaniel',
  'Bracco Italiano',
  'Braque D\'auvergne',
  'Braque De L\'ariége',
  'Braque Du Bourbonnais',
  'Braque Francais - Type Pyrénées',
  'Braque Francais -Type Gascogne',
  'Braque St-Germain',
  'Drentsche Patrijshond',
  'Fransk Spaniel',
  'Fransk Vorstehhund Strih./Korthals',
  'Gammel Dansk Hønsehund',
  'Italiensk Spinone',
  'Perdiguero De Burgos',
  'Picard Spaniel',
  'Pont-Audemer Spaniel',
  'Portugisisk Pointer',
  'Pudelpointer',
  'Slovakisk Vorstehhund Strihåret',
  'Stabijhoun',
  'Český Fousek',
  'Ungarsk Vizsla Korthåret',
  'Ungarsk Vizsla Strihåret',
  'Weimaraner Korthåret',
  'Weimaraner Langhåret',
  // Gruppe 8 - Retrievers and Water Dogs
  'Barbet',
  'Kooikerhund',
  'Lagotto Romagnolo',
  'Portugisisk Vannhund',
  'Spansk Vannhund',
  'Wetterhoun',
  'Chesapeake Bay Retriever',
  'Curly Coated Retriever',
  'Flat Coated Retriever',
  'Golden Retriever',
  'Labrador Retriever',
  'Nova Scotia Duck Tolling Retriever',
  'Amerikansk Cocker Spaniel',
  'Amerikansk Vannspaniel',
  'Clumber Spaniel',
  'Cocker Spaniel',
  'Engelsk Springer Spaniel',
  'Field Spaniel',
  'Irsk Vannspaniel',
  'Sussex Spaniel',
  'Wachtelhund',
  'Welsh Springer Spaniel',
  // Gruppe 9 - Companion and Toy Dogs
  'Bichon Frisé',
  'Bichon Havanais',
  'Bolognese',
  'Boston Terrier',
  'Cavalier King Charles Spaniel',
  'Chinese Crested',
  'Chinese Crested Powder Puff',
  'Coton De Tulear',
  'Fransk Bulldog',
  'Japanese Chin',
  'King Charles Spaniel',
  'Kromfohrländer',
  'Løwchen',
  'Malteser',
  'Mops',
  'Papillon',
  'Pekingeser',
  'Phalène',
  'Prazsky Krysarik',
  'Russian Toy, Korthåret',
  'Russian Toy, Langhåret',
  'Russisk Tsvetnaya Bolonka',
  'Dvergpuddel',
  'Mellompuddel',
  'Stor Puddel',
  'Toy Puddel',
  'Griffon Belge',
  'Griffon Bruxellois',
  'Petit Brabancon',
  'Chihuahua Korthåret',
  'Chihuahua Langhåret',
  'Lhasa Apso',
  'Shih Tzu',
  'Tibetansk Spaniel',
  'Tibetansk Terrier',
  // Gruppe 10 - Sight Hounds
  'Afghansk Mynde',
  'Azawakh',
  'Borzoi',
  'Greyhound',
  'Irsk Ulvehund',
  'Italiensk Mynde',
  'Polsk Mynde',
  'Saluki',
  'Skotsk Hjortehund',
  'Sloughi',
  'Spansk Galgo',
  'Ungarsk Mynde',
  'Whippet',
];
