import 'package:hive/hive.dart';
import 'package:breedly/models/dog.dart';
import 'package:breedly/models/litter.dart';
import 'package:breedly/models/puppy.dart';
import 'package:breedly/models/puppy_weight_log.dart';
import 'package:breedly/models/buyer.dart';
import 'package:breedly/models/expense.dart';
import 'package:breedly/models/income.dart';
import 'package:breedly/models/treatment_plan.dart';
import 'package:breedly/models/gallery_image.dart';
import 'package:breedly/models/temperature_record.dart';
import 'package:breedly/models/health.dart';
import 'package:breedly/models/vaccine.dart';
import 'package:breedly/models/progesterone_measurement.dart';
import 'package:breedly/models/purchase_contract.dart';
import 'package:breedly/models/mating.dart';
import 'package:breedly/models/kennel_profile.dart';
import 'package:breedly/models/show_result.dart';
import 'package:breedly/models/vet_visit.dart';
import 'package:breedly/models/medical_treatment.dart';
import 'package:breedly/models/dna_test.dart';
import 'package:breedly/models/weight_record.dart';
import 'package:breedly/models/delivery_checklist.dart';
import 'package:breedly/models/breeding_contract.dart';
import 'package:breedly/models/co_ownership_contract.dart';
import 'package:breedly/models/foster_contract.dart';
import 'package:breedly/models/reservation_contract.dart';
import 'package:breedly/models/kennel.dart';
import 'package:breedly/models/kennel_member.dart';
import 'package:breedly/models/kennel_invitation.dart';
import 'package:breedly/models/feed_post.dart';

/// Initialiserer alle Hive adapters og åpner bokser
Future<void> initializeHive() async {
  // Register all adapters
  Hive.registerAdapter(LitterAdapter());
  Hive.registerAdapter(DogAdapter());
  Hive.registerAdapter(PuppyAdapter());
  Hive.registerAdapter(PuppyWeightLogAdapter());
  Hive.registerAdapter(BuyerAdapter());
  Hive.registerAdapter(ExpenseAdapter());
  Hive.registerAdapter(IncomeAdapter());
  Hive.registerAdapter(TreatmentPlanAdapter());
  Hive.registerAdapter(GalleryImageAdapter());
  Hive.registerAdapter(TemperatureRecordAdapter());
  Hive.registerAdapter(HealthInfoAdapter());
  Hive.registerAdapter(VaccineAdapter());
  Hive.registerAdapter(ProgesteroneMeasurementAdapter());
  Hive.registerAdapter(PurchaseContractAdapter());
  Hive.registerAdapter(MatingAdapter());
  Hive.registerAdapter(KennelProfileAdapter());
  Hive.registerAdapter(ShowResultAdapter());
  Hive.registerAdapter(VetVisitAdapter());
  Hive.registerAdapter(MedicalTreatmentAdapter());
  Hive.registerAdapter(DnaTestAdapter());
  Hive.registerAdapter(WeightRecordAdapter());
  Hive.registerAdapter(DeliveryChecklistAdapter());
  Hive.registerAdapter(DeliveryChecklistItemAdapter());
  Hive.registerAdapter(BreedingContractAdapter());
  Hive.registerAdapter(CoOwnershipContractAdapter());
  Hive.registerAdapter(FosterContractAdapter());
  Hive.registerAdapter(ReservationContractAdapter());
  Hive.registerAdapter(KennelAdapter());
  Hive.registerAdapter(KennelMemberAdapter());
  Hive.registerAdapter(KennelInvitationAdapter());
  Hive.registerAdapter(FeedPostAdapter());

  // Open all boxes
  await Hive.openBox<Litter>('litters');
  await Hive.openBox<Dog>('dogs');
  await Hive.openBox<Puppy>('puppies');
  await Hive.openBox<PuppyWeightLog>('weight_logs');
  await Hive.openBox<Buyer>('buyers');
  await Hive.openBox<Expense>('expenses');
  await Hive.openBox<Income>('incomes');
  await Hive.openBox<TreatmentPlan>('treatment_plans');
  await Hive.openBox<GalleryImage>('gallery_images');
  await Hive.openBox<TemperatureRecord>('temperature_records');
  await Hive.openBox<HealthInfo>('health_info');
  await Hive.openBox<Vaccine>('vaccines');
  await Hive.openBox<ProgesteroneMeasurement>('progesterone_measurements');
  await Hive.openBox<PurchaseContract>('purchase_contracts');
  await Hive.openBox<Mating>('matings');
  await Hive.openBox<KennelProfile>('kennel_profile');
  await Hive.openBox<ShowResult>('show_results');
  await Hive.openBox<VetVisit>('vet_visits');
  await Hive.openBox<MedicalTreatment>('medical_treatments');
  await Hive.openBox<DnaTest>('dna_tests');
  await Hive.openBox<WeightRecord>('weight_records');
  await Hive.openBox<DeliveryChecklist>('delivery_checklists');
  await Hive.openBox<BreedingContract>('breeding_contracts');
  await Hive.openBox<CoOwnershipContract>('co_ownership_contracts');
  await Hive.openBox<FosterContract>('foster_contracts');
  await Hive.openBox<ReservationContract>('reservation_contracts');
  await Hive.openBox<Kennel>('kennel');
  await Hive.openBox<FeedPost>('feed_posts');
}
